-   id: check-undeclared
    name: FawltyDeps-undeclared
    description: "FawltyDeps: Check for undeclared dependencies"
    entry: fawltydeps --check-undeclared
    language: python
    args: [--code]
    types_or: [python, jupyter]

-   id: check-unused
    name: FawltyDeps-unused
    description: "FawltyDeps: Check for unused dependencies"
    entry: fawltydeps --check-unused
    language: python
    args: [--deps]
    files: "(.*requirements.*\\.(txt|in)|pyproject\\.toml|setup\\.(py|cfg))"
