# https://github.com/marketplace/actions/python-poetry-action
# https://github.com/snok/install-poetry
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: CI

on: [push, pull_request]

jobs:
  ci:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      #---------------------------------------------
      # install project and its dependencies
      #----------------------------------------------
      - name: Install project
        run: poetry install --no-interaction
      #----------------------------------------------
      #  run checks
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest tests/
      - name: Run type checker
        run: poetry run mypy fawltydeps tests
      - name: Run <black> linter checker
        run: poetry run black fawltydeps tests --check 
      - name: Run import sort checker
        run: poetry run isort fawltydeps tests --check-only
