name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
    
# Reference: https://squidfunk.github.io/mkdocs-material/publishing-your-site/#github-pages
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'poetry'
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: poetry sync --no-interaction --with=docs
      - run: poetry run mkdocs -- gh-deploy --force
