name: Publish to PyPI

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
  publish:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.5.1" # support for Python 3.7 was dropped in 1.6.0
      - name: Configure access
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
      - name: Build and publish package
        run: poetry publish --build -r testpypi
