name: Self test

on: [workflow_call]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.5.1" # support for Python 3.7 was dropped in 1.6.0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-self-test-${{ hashFiles('poetry.lock') }}
      - name: Install project
        run: poetry install --no-interaction --sync --with=nox,test,lint,format,dev
      - name: Run fawltydeps on Python ${{ matrix.python-version }}
        run: poetry run nox --no-venv --no-install --non-interactive -s self_test -- -vv
